@startuml
'https://plantuml.com/class-diagram

class Cliente{
    String nombre
    String apellido
    String email
    String direccion
    List<Orden> ordenes
    ordenar(unaCaja): void
}

Cliente -->"*" Orden

class Orden{
    Cliente cliente
    Date fechaCreacion
    Fabricante fabricante
    Caja cajita
    String direccionEnvio
    EstadoOrden estado
    tiempoEstimadoFabricacion(): int
    tiempoEstimadoTotal(): int
    direccionEnvio(): string
    precio(): int
    getEstadoOrden(): EstadoOrden
}
Orden --> Caja
Orden --> Fabricante
Orden --> EstadoOrden

enum EstadoOrden{
    PENDIENTE
    ENTREGADO
}


class Caja{
    Melodia melodia
    precio(): int
    tiempoEntregaEstimado(): date
}

Caja --> Melodia


interface Melodia{
    precio(): int
    nombre(): string
    tiempoEntregaEstimado(): date
}

class MelodiaDeCatalogo implements Melodia{
    precio(): int
    nombre(): string
    tiempoEntregaEstimado(): date
}

class MelodiaPersonalizada implements Melodia{
    String MIDI
    MP3 Melodia // melodia cargada por el usuario
    Validacion validacion
    Int longitudMelodia // en segundos
    List<medioDeComunicacion> mediosComunicacion
    precio(): int
    nombre(): string
    tiempoEntregaEstimado(): date
    marcarComoValida()
    marcarComoInvalida()
    notificar(): void
    cargar(melodia): void
    convertir(): string
}

MelodiaPersonalizada --> Validacion

'enum con compartamiento
enum Validacion{
    VALIDA
    INVALIDA
    marcarComoValida(): Validacion
    marcarComoInvalida(): Validacion
}

interface MIDIConverter{
string convert(byte[] melody)
}

class AdapaterMIDIConverter implements MIDIConverter{
    convertir(melodia)
}

MelodiaPersonalizada --> AdapaterMIDIConverter
MelodiaPersonalizada -->"*" MedioDeComunicacion

class Planificador{
    encolarConversiones(MelodiaPersonalizada)
    procesorConversiones()
}

Planificador -->"*" MelodiaPersonalizada

interface MedioDeComunicacion{
    recibirNotificacion(destinatario, Mensaje)
}

class MailSender implements MedioDeComunicacion{
    send(adress, subject, body)
    recibirNotificacion(destinatario, Mensaje)
}

class Whatsapp implements MedioDeComunicacion{
    (...)
    recibirNotificacion(destinatario, Mensaje)
}

Fabricante -->"*" Orden

class Fabricante{
    string nombre
    string direccion
    int capacidadProduccion
    List <Orden> ordenesAsignadas
    puedeAceptar(unaOrden): boolean
    asignar(unaOrden)
    tiempoFabricacion(): int
    getOrdenesAsignadas(): orden
}

@enduml