@startuml
'https://plantuml.com/class-diagram

class Cliente{
String nombre
String apellido
String email
String direccion
List<Orden> ordenes
ordenar(unaCaja)
}

Cliente -->"*" Orden

class Orden{
Date fechaCreacion
Fabricante fabricante
CajaMusical cajita
String direccionEnvio
tiempoEstimadoFabricacion()
tiempoEstimadoTotal()
direccionEnvio(): string
precio(): int
estado():
}
Orden --> Fabricante
Orden --> CajaMusical

interface CajaMusical{
precio(): int
nombre(): string
tiempoEntregaEstimado(): date
reproducir(self)
}

class CajaDeCatalogo implements CajaMusical{
precio(): int
nombre(): string
tiempoEntregaEstimado(): date
reproducir(self)
}

class CajaPersonalizada implements CajaMusical{
String MIDI
Validacion validacion
Int longitudMelodia // en segundos
List<medioDeComunicacion> mediosComunicacion
precio(): int
nombre(): string
tiempoEntregaEstimado(): date
marcarComoValida()
marcarComoInvalida()
notificar(): void
reproducir(self)
cargar(melodia)
}

CajaPersonalizada --> Validacion
'enum con compartamiento
enum Validacion{
VALIDA
INVALIDA
marcarComoValida(): Validacion
marcarComoInvalida(): Validacion
}

interface MIDIConverter{
string convert(byte[] melody)
}

class AdapaterMIDIConverter implements MIDIConverter{
    convertir(melodia)
}

CajaPersonalizada --> AdapaterMIDIConverter
CajaPersonalizada -->"*" MedioDeComunicacion

interface MedioDeComunicacion{
    recibirNotificacion()
}

class MailSender implements MedioDeComunicacion{
send(adress, subject, body)
}

class Whatsapp implements MedioDeComunicacion{
(...)
}

Fabricante -->"*" Orden

class Fabricante{
string nombre
string direccion
int capacidadProduccion
List <Orden> ordenesAsignadas
puedeAceptar(unaOrden): boolean
asignar(unaOrden)
tiempoFabricacion()
}

@enduml