@startuml
'https://plantuml.com/class-diagram

class Iniciador{
    List<ProcesoFirma> ProcesosDeFirma
    Plan planContratado
    iniciarProcesoFirma(Documento, Orden): void
    agregarColaborador(ProcesoFirma, Colaborador)
    anular(procesoFirma)
    restarUnProcesoDeFirmaMensual()
}

Iniciador -->"*" ProcesoFirma
Iniciador --> Plan
Iniciador --> Colaborador

' Planes: Plata, bronce, oro. para cada uno se hará
' una instancia del objeto/class Plan
class Plan{
    int cantProcesosFirmaMensuales;
    puedeCrearProcesoFirma();
}


class ProcesoFirma{
    List<Colaborador> colaboradores
    Orden orden
    Estado estado
    Iniciador iniciador
    List<Firmante> colaboradoresQueFirmaron
    List<Lector> colaboradoresQueLeyeron
    PDF Documento
    List<MedioDeNotificacion> mediosDeNotificacion

    ProcesoFirma(PDF Documento) //constructor
    agregarColaborador(Colaborador): void
    liberarDocumento(): void // hay que notificar colaboradores
    puedeVer(Colaborador): Bool
    puedeFirmar(Colaborador): Bool
    puedeLeer(Colaborador): Bool
    quienesLeyeron(): List<Lector>
    quienesFirmaron(): List<Firmante>
    estaLiberado(): Estado
    finalizar(): void
    firmar(Colaborador): void
    leer(Colaborador): void

    notificar(Colaborador/Iniciador, ProcesoFirma, Mensaje)
}

ProcesoFirma --> Orden
ProcesoFirma --> Estado
ProcesoFirma -->"*" Colaborador
ProcesoFirma --> AdapterGeneradorDeFirmas

interface GeneradorDeFirma{
    generarFirma(nombre, apellido, email, telefono): String
}

class AdapterGeneradorDeFirmas implements GeneradorDeFirma{
    generarFirma(Colaborador): String
}

enum Orden{
    INDISTINTO
    PREFIJADO
}

enum Estado{
    NO_LIBERADO
    LIBERADO
    FINALIZADO
}

Firmante ..> ProcesoFirma
Lector ..> ProcesoFirma

abstract Colaborador{
    String nombre
    String apellido
    String email
    String telefono
    List<ProcesoFirma> DocumentosQueColabora
}

class Firmante extends Colaborador{
    cargarDatos(procesoFirma): void
    firmar(procesoFirma): void
}

class Lector extends Colaborador{
    leer(procesoFirma): void
}

ProcesoFirma -->"*" MedioDeNotificacion

interface MedioDeNotificacion{
    recibirNotificacion(destinatario, mensaje): void
}

class MailSender implements MedioDeNotificacion{
    recibirNotificacion(destinatario, mensaje): void
}

class NotificacionDeAplicacion implements MedioDeNotificacion{
    recibirNotificacion(destinatario, mensaje): void
}

class SMS implements MedioDeNotificacion{
    recibirNotificacion(destinatario, mensaje): void
}

@enduml